apiVersion: v1
kind: LimitRange
metadata:
  name: rahma-default-limits
  namespace: rahma-data
spec:
  limits:
    - type: Container
      default:
        cpu: "1000m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rahma-default-limits
  namespace: rahma-ai
spec:
  limits:
    - type: Container
      default:
        cpu: "2000m"
        memory: "4Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
