apiVersion: v1
kind: Namespace
metadata:
  name: rahma-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-mobile-build
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-rag
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-security
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-wasm
---
apiVersion: v1
kind: Namespace
metadata:
  name: rahma-workers