apiVersion: v1
kind: Namespace
metadata:
  name: rahma-ai
  labels:
    app.kubernetes.io/part-of: rahma
    app.kubernetes.io/managed-by: k3s
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
