apiVersion: v1
kind: Secret
metadata:
  name: rahma-api-secrets-example
  namespace: rahma-api
  labels:
    app.kubernetes.io/name: rahma-api
    app.kubernetes.io/part-of: rahma
  annotations:
    rahma.serverax.io/template-only: "true"
type: Opaque
stringData:
  DATABASE_URL: CHANGE_ME_POSTGRES_URL
  SESSION_SECRET: CHANGE_ME_SESSION_SECRET
  AUTH_SECRET: CHANGE_ME_AUTH_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: rahma-postgres-secrets-example
  namespace: rahma-data
  labels:
    app.kubernetes.io/name: rahma-postgres
    app.kubernetes.io/part-of: rahma
  annotations:
    rahma.serverax.io/template-only: "true"
type: Opaque
stringData:
  POSTGRES_DB: rahma
  POSTGRES_USER: rahma_user
  POSTGRES_PASSWORD: CHANGE_ME_POSTGRES_PASSWORD
